import Head from 'next/head'
import { loadStripe } from '@stripe/stripe-js';

const stripePromise = loadStripe('pk_test_51NfpJ8I7NVJoEH9a9n3BS92cvZlxZ5NSZBbH0Q2fUqnp81Gm4apHnSZ9Ezsy3xXIw67kmnHwYgXiy8ljZHaXjfoV00RcTP8Iku');


export default function Home() {
  const handleCheckout = async () => {
    try {
      // Fetch the checkout session ID from the backend
      const response = await fetch('http://localhost:4242/create-checkout-session', {
        method: 'POST'
      });
      const session = await response.json();

      // Load the Stripe library
      const stripe = await stripePromise;

      // Redirect to the Stripe checkout
      const result = await stripe.redirectToCheckout({
        sessionId: session.id
      });

      if (result.error) {
        alert(result.error.message);
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  return (
    <>
      <Head>
        <title>Stripe Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Welcome to Stripe Store</h1>
            <button onClick={handleCheckout}>Buy Now</button>
        </div>
      </main>
    </>
  )
}
